name: asd
on:
  push:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  fetch-apk:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://github.com/jayluxferro/APK-Downloader.git
      - run: pip install -r APK-Downloader/requirements.txt
      - run: python APK-Downloader/apk-downloader.py com.kevinforeman.nzb360
      - run: mv *.apk nzb360.apk
      - uses: actions/upload-artifact@v1
        with:
          name: nzb360.apk
          path: nzb360.apk
  patch:
    needs: fetch-apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - run: curl -LO https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool && chmod +x apktool
        working-directory: /usr/local/bin
      - run: curl -L -o apktool.jar https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.5.0.jar && chmod +x apktool.jar
        working-directory: /usr/local/bin
      - uses: actions/download-artifact@v2
        with:
          name: nzb360.apk
          path: .
      - run: apktool d nzb360.apk
      - run: TO_PATCH=$(grep -rl 'const-string p1, "valid"' nzb360) || exit 1; sed -i 's/const-string p1, "valid"/move-object p1, p3/' $TO_PATCH
      - run: apktool b --use-aapt2 -o ../nzb360_mod.apk
        working-directory: nzb360
      - uses: actions/upload-artifact@v2
        with:
          name: nzb360_mod.apk
          path: nzb360_mod.apk
  sign:
    needs: patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v2
        with:
            distribution: 'adopt'
            java-version: '8'
      - run: curl -L -o uber-apk-signer.jar https://github.com/patrickfav/uber-apk-signer/releases/download/v1.2.1/uber-apk-signer-1.2.1.jar && chmod +x uber-apk-signer.jar
      - uses: actions/download-artifact@v2
        with:
          name: nzb360_mod.apk
          path: .
      - run: java -jar uber-apk-signer.jar -a nzb360_mod.apk
      - run: mv nzb360_mod-aligned-debugSigned.apk nzb360_mod_signed.apk
      - uses: actions/upload-artifact@v2
        with:
          name: nzb360_mod_signed.apk
          path: nzb360_mod_signed.apk
  publish:
    needs: sign
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: nzb360_mod_signed.apk
          path: .
      - run: curl https://api.telegram.org/bot$TG_BOT_TOKEN/sendDocument -F chat_id=$TG_CHAT_ID -F document=@nzb360_mod_signed.apk
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}